/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Representation of a country reference
 *
 * @param isoCode Country ISO code
 */
@Serializable

data class CountryReference (

    /* Country ISO code */
    @SerialName(value = "isoCode") @Required val isoCode: kotlin.String

) {


}

