/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CountryReference
import org.openapitools.client.models.HolidayQuality
import org.openapitools.client.models.HolidayType
import org.openapitools.client.models.LocalizedText
import org.openapitools.client.models.SubdivisionReference

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Representation of a holiday by date
 *
 * @param country 
 * @param id Unqiue holiday id
 * @param name Localized names of the holiday
 * @param nationwide Is the holiday nationwide?
 * @param subdivisions List of subdivision references
 * @param type 
 * @param comment Additional localized comments
 * @param quality 
 */
@Serializable

data class HolidayByDateResponse (

    @SerialName(value = "country") @Required val country: CountryReference,

    /* Unqiue holiday id */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Localized names of the holiday */
    @SerialName(value = "name") @Required val name: kotlin.collections.List<LocalizedText>,

    /* Is the holiday nationwide? */
    @SerialName(value = "nationwide") @Required val nationwide: kotlin.Boolean,

    /* List of subdivision references */
    @SerialName(value = "subdivisions") @Required val subdivisions: kotlin.collections.List<SubdivisionReference>,

    @SerialName(value = "type") @Required val type: HolidayType,

    /* Additional localized comments */
    @SerialName(value = "comment") val comment: kotlin.collections.List<LocalizedText>? = null,

    @SerialName(value = "quality") val quality: HolidayQuality? = null

) {


}

