/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LocalizedText

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Representation of a language as defined in ISO-639-1
 *
 * @param isoCode ISO-639-1 language code
 * @param name Localized language names
 */
@Serializable

data class LanguageResponse (

    /* ISO-639-1 language code */
    @SerialName(value = "isoCode") @Required val isoCode: kotlin.String,

    /* Localized language names */
    @SerialName(value = "name") @Required val name: kotlin.collections.List<LocalizedText>

) {


}

