/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A localized text string
 *
 * @param language ISO-639-1 language code
 * @param text The localized text
 */
@Serializable

data class LocalizedText (

    /* ISO-639-1 language code */
    @SerialName(value = "language") @Required val language: kotlin.String,

    /* The localized text */
    @SerialName(value = "text") @Required val text: kotlin.String

) {


}

