/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Statistical data of the holidays database
 *
 * @param youngestStartDate The youngest holiday start date in the database
 * @param oldestStartDate The oldest holiday start date in the database
 */
@Serializable

data class StatisticsResponse (

    /* The youngest holiday start date in the database */
    @SerialName(value = "youngestStartDate") @Required val youngestStartDate: kotlinx.datetime.LocalDate,

    /* The oldest holiday start date in the database */
    @SerialName(value = "oldestStartDate") @Required val oldestStartDate: kotlinx.datetime.LocalDate

) {


}

