/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LocalizedText

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Representation of a subdivision
 *
 * @param category Localized categories of the subdivision
 * @param code Subdivision code
 * @param comment Localized comments of the subdivision
 * @param name Localized names of the subdivision
 * @param officialLanguages Official languages as ISO-639-1 codes
 * @param shortName Short name for display
 * @param children Child subdivisions
 * @param isoCode ISO 3166-2 subdivision code (if defined)
 */
@Serializable

data class SubdivisionResponse (

    /* Localized categories of the subdivision */
    @SerialName(value = "category") @Required val category: kotlin.collections.List<LocalizedText>,

    /* Subdivision code */
    @SerialName(value = "code") @Required val code: kotlin.String,

    /* Localized comments of the subdivision */
    @SerialName(value = "comment") @Required val comment: kotlin.collections.List<LocalizedText>,

    /* Localized names of the subdivision */
    @SerialName(value = "name") @Required val name: kotlin.collections.List<LocalizedText>,

    /* Official languages as ISO-639-1 codes */
    @SerialName(value = "officialLanguages") @Required val officialLanguages: kotlin.collections.List<kotlin.String>,

    /* Short name for display */
    @SerialName(value = "shortName") @Required val shortName: kotlin.String,

    /* Child subdivisions */
    @SerialName(value = "children") val children: kotlin.collections.List<SubdivisionResponse>? = null,

    /* ISO 3166-2 subdivision code (if defined) */
    @SerialName(value = "isoCode") val isoCode: kotlin.String? = null

) {


}

