name: Deploy to GitHub

on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/gradle.yml
    with:
      openai-api-key: ${{ secrets.OPENAI_API_KEY }}
      gradle-cache-encryption-key: ${{ secrets.GRADLEENCRYPTIONKEY }}
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Download macOS ARM build
#        uses: actions/download-artifact@v4
#        with:
#          name: build-macOS
#          path: ./artifacts
#
#      - name: Download Windows build
#        uses: actions/download-artifact@v4
#        with:
#          name: build-Windows
#          path: ./artifacts

      - name: Download Ubuntu build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./composeApp/build

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: -v make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1